### ISSUE TITLE
PDF example fails

### ISSUE THREAD

**Issue by dvn0** [Bogdanp/marionette#2]
Hello again!

Enjoying learning from this library.

The PDF example fails for me with a timeout error. I tried running the javascript with another marionette client, and got the same error: `Timed out after 30000 ms`

Does it work for you though?

**Comment by Bogdanp** [comment]
Yes, it does work for me, but the PDF it generates isn't exactly usable. Did you change the page URL by any chance?  The script will fail on any page that has a content security policy that doesn't include those two CDNs it references.
