### ISSUE TITLE
match-define: no matching clause for #f in private\transport.rkt

### ISSUE THREAD

**Issue by kurinoku** [Bogdanp/marionette#4]
To be honest, I forgot why this happened... but the error was this.
`\7.9\pkgs\marionette-lib\marionette\private\transport.rkt:85:2: match-define: no matching clause for #f`

Leaving it here just in case, but could have been an user (my) error.

**Comment by Bogdanp** [comment]
Thanks for the report. Could you share the version of Firefox you're using and the OS?

**Comment by Bogdanp** [comment]
#6 should have resolved this issue.
