### ISSUE TITLE
Iframe support

### ISSUE THREAD

**Issue by db7** [Bogdanp/marionette#9]
Thanks for the library. It’s super easy to use. 👍

In one use case, however, I cannot find a satisfying solution. I need to access elements inside an iframe. I can find the iframe with page-query-selector. But how can I proceed to search inside the iframe in an **elegant** way?

My current hack is to run a JavaScript command with page-execute replacing the InnerHTML of the page with the InnerHTML of the iframe. After that I can use page-query-selector in the iframe. I find solution is quite ugly. Do you have a better approach?

**Comment by Bogdanp** [comment]
Thanks! The latest commit adds a couple procedures you can use to work with frames. There is also an example in case it helps.
